default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rails
  password: rails
  host: localhost
  port: 5432

development:
  <<: *default
  database: teacher_developement1

# test:
#   <<: *default
#   database: teacher_test

# production:
#   <<: *default
#   database: teacher_production